version: '3.1'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
#    volumes:
#      - ./mongo_data:/data/db
#    env_file:
#      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
