name: CI-‌Frontend-test

on:
  push:
    branches: main
env:
 # DOCKER_REGISTRY: 
 # DOCKER_REPOSITORY: 
  image_name: frontend

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
  #    - name: Set up QEMU
  #      uses: docker/setup-qemu-action@v2

      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
   #       username: ${{ secrets.DOCKERHUB_USERNAME }}
          username: leylahosseini
          password: ${{ secrets.TOKEN }}
          registry: ghcr.io/leylahosseini/

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            GIT_TOKEN=${{ secrets.TOKEN }}
          tags: ghcr.io/leylahosseini/frontend_dev:${{ github.sha }}

      - name: Update Version
        run: |
          git config --global user.email "slaila.hosseini@gmail.com"
          git config --global user.name "leylahosseini"
          git clone https://${{ secrets.TOKEN }}@github.com/leylahosseini/test-argocd.git
          git clone https://github.com/leylahosseini/test-argocd.git
          cd test-argocd/app

          tag=$(cat ./values-dev.yaml | grep frontend_image | awk -F":" '{print $3}') 
          sed -i "s/$tag/${{ github.sha }}/" ./values-dev.yaml


          git add .
          git commit -m "enginedevops/frontend-dev/${{ github.sha }}"
          git push
