name: CI-‌Frontend-DEV

on:
  push:
    branches: develop
env:
 # DOCKER_REGISTRY: 
 # DOCKER_REPOSITORY: 
  image_name: frontend

jobs:
  build:
    name: Building and Pushing the Image
#    runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
      - name: checkout
        uses: actions/checkout@v2
#        with:
#          submodules: recursive
#          token: ${{ secrets.TOKEN_CLASSIC }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: ${{ secrets.DOCKERHUB_URL }}
#          username: leylahosseini
#          password: ${{ secrets.TOKEN_CLASSIC }}          
#          registry: ghcr.io/leylahosseini/

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
#            GIT_TOKEN=${{ secrets.TOKEN_CLASSIC }}
#          tags: ghcr.io/leylahosseini/frontend_dev:${{ github.sha }}
          tags:  enginedevops/frontend_dev:${{ github.sha }}       
   
      - name: Update Version
        run: |
          git config --global user.email "slaila.hosseini@gmail.com"
          git config --global user.name "leylahosseini"
          git clone https://${{ secrets.TOKEN_CLASSIC }}@github.com/leylahosseini/test-argocd.git
          cd test-argocd/app

          tag=$(grep frontend_image values-dev.yaml| awk -F ":" '{print $3}') 
          sed -i "s/$tag/${{ github.sha }}/" ./values-dev.yaml
          
          git add .
          git commit -m "enginedevops/frontend_dev/${{ github.sha }}"
          git push
